[application]

# dioxus project name
name = "dioxus-bundle-sample"

# default platfrom
# you can also use `dx serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "desktop"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "放射科 360 小助手"

[web.watcher]

index_on_404 = true

watch_path = ["src"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[application.plugins]

available = false

required = []

[bundle]
# Bundle identifier
identifier = "com.heyrict.dioxus-bundle-sample"

# Bundle publisher
publisher = "heyrict"

# Bundle icon
icon = ["assets/icon.ico"]

# Bundle resources
resources = ["assets/*"]

# Bundle copyright
copyright = "Copyright (c) heyrict 2023. All rights reserved."

# Bundle short description
short_description = "Dioxus"

[bundle.windows]
allow_downgrades = true
webview_install_mode = { FixedRuntime = { path = "packages/webview2" } }
tsp = true
icon_path = "assets/icon.ico"
