name: Main workflow
on:
  push: {}
  pull_request: {}
jobs:
  build:
    name: Compile & Release
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: dioxus-bundle-sample-x86_64-pc-windows-msvc.zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Setup | 7zip [Windows]
        if: matrix.os == 'windows-latest'
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install wget 7zip.portable

      - name: Fetch webview2 runtime [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          wget 'https://github.com/westinyang/WebView2RuntimeArchive/releases/download/109.0.1518.78/Microsoft.WebView2.FixedVersionRuntime.109.0.1518.78.x64.cab'
          7z x 'Microsoft.WebView2.FixedVersionRuntime.109.0.1518.78.x64.cab'
          mkdir -p packages/
          mv 'Microsoft.WebView2.FixedVersionRuntime.109.0.1518.78.x64' packages/webview2

      - uses: Swatinem/rust-cache@v2

      - name: Install dioxus-cli [Windows]
        run: |
          git clone https://github.com/heyrict/dioxus --branch windows-bootstrap --depth=1
          cargo install --path dioxus/packages/cli

      - name: Format-print config
        run: dx config format-print

      - name: Build target [Windows]
        run: dx bundle --release --platform desktop

      - name: Prepare build artifacts [Windows]
        run: |
          7z a ${{ matrix.name }} dist\bundle

      - name: Release | Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}
